Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,6 +29,17 @@ jobs:
         with:
           path: LuaUnlocker
 
+      - name: Verify Protobuf Directory
+        run: |
+          ls -R
+          if [ -d "protobuf" ]; then
+            echo "Protobuf directory found."
+            ls protobuf
+          else
+            echo "Protobuf directory not found!"
+            exit 1
+          fi
+
       - name: Checkout Metamod
         uses: actions/checkout@v4
         with:
@@ -65,7 +76,7 @@ jobs:
         shell: bash
         run: |
           mkdir build && cd build
-          python ../configure.py --enable-optimize --symbol-files --sdks cs2 --include-dir protobuf/generated
+          python ../configure.py --enable-optimize --symbol-files --sdks cs2 --include-dir ../protobuf/generated
           ambuild
 
       - name: Upload artifact
